steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/maxximus-website/maxximusimg:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/maxximus-website/maxximusimg:latest']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'maxximus-website', '--image', 'gcr.io/maxximus-website/maxximusimg:latest', '--region', 'us-east1', '--platform', 'managed']

images:
- 'gcr.io/maxximus-website/maxximusimg:latest' 